name: Java CI with Maven

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
    
  test-report:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1.6.0
        with:
          path: target/test-results.xml
          reporter: java-junit
