name: Java CI with Maven and Extent Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean test --file pom.xml     
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --local user.email "sucar661@gmail.com"
          git config --local user.name "serhat-project"

      - name: Transfer Extent Report to gh-pages
        run: |
          # Check if authentication token is set
          if [ -z "${{ secrets.MYTOKEN }}" ]; then
            echo "Authentication token not set. Exiting workflow."
            exit 1
          fi

          # Copy the extent report to the gh-pages branch
          cp -r test-output/ExtentReport gh-pages/reports

          # Modify the report.html name by appending a string ID and timestamp
          mv gh-pages/reports/report.html gh-pages/reports/SmokeTest$(date +"%Y%m%d%H%M%S").html

          # Add and push the changes to the gh-pages branch
          git add gh-pages/reports/SmokeTest$(date +"%Y%m%d%H%M%S").html
          git commit -m "Update extent report"
          git push origin gh-pages
