name: Java CI with Maven and Extent Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean test --file pom.xml
      - name: Generate Extent Report
        run: mvn test-compile exec:java -Dexec.mainClass="runners.Runner"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload Extent Report to gh-pages
        uses: PavanMudigonda/html-reporter-github-pages@v1.2
        with:
          test_results: test-output/ExtentReport
          keep_reports: 20
          gh_pages: gh-pages
          subfolder: reports
          tool_name: cucumber
          workflow_name: ${{ github.workflow }}
          report_name: "${{ github.workflow }}+${{ github.run_id }}+${{ github.run_started_at }}.html"

