name: Java CI with Maven and Extent Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean test --file pom.xml
        
      # Generate a report folder and move the test results to it
      - name: Generate Report
        run: |
          mkdir -p report
          mv -f test-output/ExtentReport/* report

      # Modify the report file name by appending a unique string and timestamp to it
      # This will ensure uniqueness and avoid overwriting existing reports
      - name: Rename Report
        run: |
          mv -f report/ExtentReport.html report/SmokeTest$(date +"%Y-%m-%d-%H-%M").html

      # Transfer the report file to the destination gh-pages branch using the GitHub Pages deploy action
      # Specify the source folder, the destination branch and a commit message
      - name: Deploy Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report
          publish_branch: gh-pages
          commit_message: "[Automation Test] Updated Report"
