name: Java CI with Maven and Extent Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean test --file pom.xml
        
      - name: Upload test results
        uses: actions/upload-artifact@v1
        with:
            name: Test Results
            path: test-output/ExtentReport #Replace with the path to your test result folder
      - name: Generate report
        run: |
            mv test-output/ExtentReport/report.html report.html #Replace with your report path and name
            git config --local user.email "sucar661@gmail.com"
            git config --local user.name "serhat-project"
      - name: Transfer report to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.MYTOKEN }} #Replace with your GitHub Personal Access Token
            publish_dir: . #Replace with the directory where your report.html file is generated
            publish_branch: gh-pages #Replace with your gh-pages branch name
           
         
