name: Java CI with Maven and Extent Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean test --file pom.xml     
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-output/ExtentReport

      - name: Modify Artifact Name
        run: |
          # Get the artifact name
          artifact_name=$(echo "${{ artifacts.test-report.name }}" | tr -d " .")

          # Add a string ID and timestamp to the artifact name
          new_artifact_name="SmokeTest$(date +"%Y%m%d%H%M%S")${artifact_name}"

          # Rename the artifact
          mv test-output/ExtentReport/${artifact_name} test-output/ExtentReport/${new_artifact_name}

      - name: Transfer Extent Report to gh-pages
        run: |
          # Check if authentication token is set
          if [ -z "${{ secrets.MYTOKEN }}" ]; then
            echo "Authentication token not set. Exiting workflow."
            exit 1
          fi

          # Get the user name
          user_name=$(echo "${{ secrets.USERNAME }}")

          # Get the repository name
          repo_name=$(echo "${{ github.Api }}")

          # Clone the repository
          git clone https://github.com/${user_name}/${repo_name} ./gh-pages

          # Switch to the gh-pages branch
          git checkout gh-pages

          # Copy the extent report to the gh-pages branch
          cp test-output/ExtentReport/${new_artifact_name} ./gh-pages

          # Add and push the changes to the gh-pages branch
          git add ./gh-pages/${new_artifact_name}
          git commit -m "Update extent report"
          git push origin gh-pages

     
